---
swagger: "2.0"
info:
  x-ibm-name: "o2apic-novum-billprofile"
  title: "O2APIC-Novum-BillProfile"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/apic"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: "invokeProperties"
        timeout: 60
        verb: "GET"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error:
        - null
        version: "1.0.0"
        target-url: "http://www.mocky.io/v2/5b04ee443200007b00ebf5f5"
        output: "Properties"
    - invoke:
        target-url: "http://www.mocky.io/v2/5b03dd232f00001610e7a71b"
        stop-on-error:
        - "ConnectionError"
        - "OperationError"
        output: "messages-uri"
        title: "InvokeURIHandler"
    - gatewayscript:
        title: "GS:GetPhoneServiceDetails"
        version: "1.0.0"
        source: "/* ***********************************************************************************************************************\
          \ */\n/* ***********************************************************************************************************************\
          \ */\n/* FileName                                Version    Created By \
          \                 Modified By               Date           */\n/* GetPhoneServiceDetails.js\
          \                1.0        Dinesh Tomar                               \
          \           08-May-2018   */\n/*                                       \
          \                                                                      \
          \            */\n/* ***********************************************************************************************************************\
          \ */\n/* Purpose: This GW Script file will extract phone service URL's from\
          \ URI Handler file.                                    */\n/*          \
          \                                                                      \
          \                                         */\n/* Required params:      \
          \                                                                      \
          \                            */\n/* ***********************************************************************************************************************\
          \ */\n//load URI's from context variable\nvar uri_messages = apim.getvariable('messages-uri.body');\n\
          //load properties configuration from context variable\nvar messages = apim.getvariable('Properties.body');\n\
          //get all headers\nvar msisdn = apim.getvariable('request.parameters.msisdn');\n\
          //var billNumber = apim.getvariable('request.parameters.billNumber');\n\n\
          //check all headers validation\nif(messages == null || isJSONEmpty(messages)){\n\
          \    apim.setvariable('errorName', 'ConnectionError');\n   apim.error('ConnectionError',\
          \ 500, 'Internal Error', 'Connection error');\n}\nelse if (msisdn == null\
          \ || msisdn == undefined){\n    apim.setvariable('errorName', 'InvalidMsisdn');\n\
          \    apim.error('InvalidMsisdn', 500, 'Internal Error', 'Missing or invalid\
          \ msisdn');\n}\nelse if (uri_messages == null || isJSONEmpty(uri_messages)){\n\
          \    apim.setvariable('errorName', 'ConnectionError');\n    apim.error('ConnectionError',\
          \ 500, 'Internal Error', 'Connection error');\n}\nelse {\n    apim.setvariable('message.headers.msisdn',\
          \ msisdn);\n    var billProfileURL = uri_messages.phoneservice.billedcharges.billprofile.uri;\n\
          \    //phoneDetailsURL = phoneDetailsURL.replace('CURRENT', apim.getvariable('message.headers.msisdn'));\n\
          \    //if(billNumber!= null)\n    //{\n       // billProfileURL = billProfileURL\
          \ + '?billnumber=' + billNumber;\n    //}\n    apim.setvariable('billProfileURL',\
          \ billProfileURL);\n    var recommendationsURL = uri_messages.phoneservice.billedcharges.recommendations.uri;\n\
          \    //phonePlanURL = phonePlanURL.replace('CURRENT', apim.getvariable('message.headers.msisdn'));\n\
          \    apim.setvariable('recommendationsURL', recommendationsURL);\n   }\n\
          \nfunction isJSONEmpty(jsonObject) {\n    var member;\n    var result =\
          \ true;\n    for (member in jsonObject) {\n        if (jsonObject[member]\
          \ != null) {\n            result = false;\n        }\n    }\n    return\
          \ result;\n}"
    - invoke:
        title: "InvokeBillProfile"
        timeout: 60
        verb: "GET"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error:
        - null
        - "ConnectionError"
        - "OperationError"
        version: "1.0.0"
        target-url: "$(billProfileURL)"
        output: "BillProfileResponse"
    - invoke:
        title: "InvokeRecommendations"
        timeout: 60
        verb: "GET"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error:
        - null
        - "ConnectionError"
        - "OperationError"
        version: "1.0.0"
        output: "RecommendationsResponse"
        target-url: "$(recommendationsURL)"
    - map:
        title: "map"
        inputs:
          input:
            schema:
              description: ""
              type: "object"
              properties:
                paymentStatus:
                  type: "string"
                  name: "paymentStatus"
                defaultLPFCharge:
                  type: "string"
                  name: "defaultLPFCharge"
                bill_amount:
                  type: "string"
                  name: "bill_amount"
                bill_date:
                  type: "string"
                  name: "bill_date"
                payment_date:
                  type: "string"
                  name: "payment_date"
                amount_due:
                  type: "string"
                  name: "amount_due"
                total_before_vat:
                  type: "string"
                  name: "total_before_vat"
                vat:
                  type: "string"
                  name: "vat"
                other_charges_and_credits:
                  type: "string"
                  name: "other_charges_and_credits"
                order_charges:
                  type: "string"
                  name: "order_charges"
                bill_period:
                  type: "object"
                  properties:
                    bill_date_from:
                      type: "string"
                      name: "bill_date_from"
                    bill_date_to:
                      type: "string"
                      name: "bill_date_to"
                  name: "bill_period"
                next_bill_date:
                  type: "string"
                  name: "next_bill_date"
                balance_brought_forward:
                  type: "string"
                  name: "balance_brought_forward"
                bill_discounts:
                  type: "string"
                  name: "bill_discounts"
                multi_msisdn:
                  type: "boolean"
                  name: "multi_msisdn"
                msisdn_billdetails_list:
                  type: "array"
                  items:
                    properties:
                      msisdn:
                        type: "string"
                        name: "msisdn"
                      billtotal_without_VAT:
                        type: "string"
                        name: "billtotal_without_VAT"
                    type: "object"
                  name: "msisdn_billdetails_list"
              example: "{\r\n    \"paymentStatus\": \"UNKNOWN\",\r\n    \"defaultLPFCharge\"\
                : \"£3.50\",\r\n    \"bill_amount\": \"£145.60\",\r\n    \"bill_date\"\
                : \"01.03.2013\",\r\n    \"payment_date\": \"10.03.2013\",\r\n   \
                \ \"amount_due\": \"£50.50\",\r\n    \"total_before_vat\": \"£125.50\"\
                ,\r\n    \"vat\": \"£20.21\",\r\n    \"other_charges_and_credits\"\
                : \"£0.00\",\r\n    \"order_charges\": \"£0.00\",\r\n    \"bill_period\"\
                : {\r\n        \"bill_date_from\": \"01.02.2013\",\r\n        \"bill_date_to\"\
                : \"01.03.2013\"\r\n    },\r\n    \"next_bill_date\": \"01.04.2013\"\
                ,\r\n    \"balance_brought_forward\": \"£25.00\",\r\n    \"bill_discounts\"\
                : \"£0.11\",\r\n    \"multi_msisdn\": true,\r\n    \"msisdn_billdetails_list\"\
                : [\r\n        {\r\n            \"msisdn\": \"447000000009\",\r\n\
                \            \"billtotal_without_VAT\": \"£30.00\"\r\n        },\r\
                \n        {\r\n            \"msisdn\": \"441111112289\",\r\n     \
                \       \"billtotal_without_VAT\": \"£44.60\"\r\n        }\r\n   \
                \ ]\r\n}"
            variable: "BillProfileResponse.body"
            content: "application/json"
          input_1:
            schema:
              description: ""
              type: "object"
              properties:
                recommendations:
                  type: "array"
                  items:
                    type: "string"
                  name: "recommendations"
              example: "{\r\n    \"recommendations\": [\"TARIFF\", \"O2_TRAVEL\",\
                \ \"PICTURE_MESSAGES\", \"INTERNATIONAL_FAVOURITES\"]\r\n}"
            variable: "RecommendationsResponse.body"
            content: "application/json"
        outputs:
          output:
            schema:
              $ref: "#/definitions/BillProfileResponse"
            variable: "message.body"
            content: "application/json"
        actions:
        - set: "output.paymentStatus"
          from: "input.paymentStatus"
        - set: "output.defaultLPFCharge"
          value: "var messages = apim.getvariable('Properties.body');\r\nmessages.defaultLPFCharge;"
        - set: "output.billAmount"
          from: "input.bill_amount"
        - set: "output.billDate"
          from: "input.bill_date"
        - set: "output.paymentDate"
          from: "input.payment_date"
        - set: "output.amountDue"
          from: "input.amount_due"
        - set: "output.totalBeforeVAT"
          from: "input.total_before_vat"
        - set: "output.taxCharges"
          from: "input.vat"
        - set: "output.otherChargesAndCredits"
          from: "input.other_charges_and_credits"
        - set: "output.orderCharges"
          from: "input.order_charges"
        - set: "output.billPeriod.billDateFrom"
          from: "input.bill_period.bill_date_from"
        - set: "output.billPeriod.billDateTo"
          from: "input.bill_period.bill_date_to"
        - set: "output.nextBillDate"
          from: "input.next_bill_date"
        - set: "output.balanceBroughtForward"
          from: "input.balance_brought_forward"
        - set: "output.billDiscounts"
          from: "input.bill_discounts"
        - set: "output.multiMsisdn"
          from: "input.multi_msisdn"
        - create: "output.msisdnBillDetails"
          foreach: "input.msisdn_billdetails_list"
          from: "input.msisdn_billdetails_list"
          actions:
          - set: "$item"
            from: "$item"
        - set: "output.extraChargesRecommendation"
          from: "input_1.recommendations"
          value: "recommendation($(input_1.recommendations));\r\nfunction recommendation(recommendations)\
            \ {\r\n    var extraChargesRecommendation = {\r\n    };\r\n    var extraChargesRecommendationResponse\
            \ = {\r\n    };\r\n    if (recommendations.length > 0) {\r\n        extraChargesRecommendationResponse\
            \ = ExtraChargesRecommendation(recommendations);\r\n        \r\n     \
            \   if (! isJSONEmpty(extraChargesRecommendationResponse) && ! isJSONEmpty(extraChargesRecommendationResponse.recommendations)\
            \ && extraChargesRecommendationResponse.recommendations.length > 0) {\r\
            \n            extraChargesRecommendation = apim.getvariable('Properties.body').recommendation.homepage.message;\r\
            \n            return extraChargesRecommendation;\r\n        }\r\n    \
            \    return null;\r\n    }\r\n    return null;\r\n}\r\n\r\nfunction ExtraChargesRecommendation(recommendation)\
            \ {\r\n    var extraChargesRecommendation = {\r\n    };\r\n    var recommendation\
            \ = setUpRecommendations(recommendation);\r\n    var hasMultipleMessages\
            \ = false;\r\n    var header = null;\r\n    if (recommendation.length\
            \ > 1) {\r\n        hasMultipleMessages = true;\r\n    }\r\n    header\
            \ = hasMultipleMessages ? apim.getvariable('Properties.body').recommendation.header:\
            \ null;\r\n    extraChargesRecommendation.hasMultipleMessages = hasMultipleMessages;\r\
            \n    extraChargesRecommendation.header = header;\r\n    extraChargesRecommendation.recommendations\
            \ = recommendation;\r\n    return extraChargesRecommendation;\r\n}\r\n\
            function setUpRecommendations(recommendation) {\r\n    var recommendationDetails\
            \ =[];\r\n    var boltOnsRecommendations = filterBoltOnRecommendationTypes(recommendation);\r\
            \n    var boltOnRecommendationDetails = getBoltOnRecommendationDetails(boltOnsRecommendations,\
            \ boltOnsRecommendations);\r\n    var tariffRecommendationDetails = getTariffRecommendationDetails(recommendation);\r\
            \n    \r\n    if (! isJSONEmpty(boltOnRecommendationDetails)) {\r\n  \
            \      recommendationDetails.push(boltOnRecommendationDetails);\r\n  \
            \  }\r\n    if (! isJSONEmpty(tariffRecommendationDetails)) {\r\n    \
            \    recommendationDetails.push(tariffRecommendationDetails);\r\n    }\r\
            \n    return recommendationDetails;\r\n}\r\nfunction filterBoltOnRecommendationTypes(recommendation)\
            \ {\r\n    var boltOnRecommendationTypes =[];\r\n    for (var i = 0; i\
            \ < recommendation.length; i++) {\r\n        if (recommendation[i] !=\
            \ 'TARIFF') {\r\n            boltOnRecommendationTypes.push(recommendation[i]);\r\
            \n        }\r\n    }\r\n    return boltOnRecommendationTypes;\r\n}\r\n\
            function getBoltOnRecommendationDetails(recommendation, boltOnsRecommendations)\
            \ {\r\n    if (! isJSONEmpty(boltOnsRecommendations)) {\r\n        for\
            \ (var i = 0; i < recommendation.length; i++) {\r\n            \r\n  \
            \          return boltOnsRecommendations.length > 1 ? createRecommendationDetails('MULTIPLE_BOLTONS'):\r\
            \n            createRecommendationDetails(recommendation[i]);\r\n    \
            \    }\r\n    }\r\n    return null;\r\n}\r\nfunction getTariffRecommendationDetails(recommendation)\
            \ {\r\n    for (var i = 0; i < recommendation.length; i++) {\r\n     \
            \   if (recommendation[i] == 'TARIFF') {\r\n            return createRecommendationDetails(recommendation[i]);\r\
            \n        }\r\n    }\r\n    \r\n    return null;\r\n}\r\nfunction createRecommendationDetails(recommendationType)\
            \ {\r\n    var recommendationDetails = {\r\n    };\r\n    recommendationDetails.Type\
            \ = apim.getvariable('Properties.body').recommendation[recommendationType].type;\r\
            \n    recommendationDetails.Action = apim.getvariable('Properties.body').recommendation[recommendationType].action;\r\
            \n    recommendationDetails.LinkText = apim.getvariable('Properties.body').recommendation[recommendationType].linkText;\r\
            \n    recommendationDetails.Message = apim.getvariable('Properties.body').recommendation[recommendationType].message;\r\
            \n    return recommendationDetails;\r\n}\r\nfunction isJSONEmpty(jsonObject)\
            \ {\r\n    var member;\r\n    var result = true;\r\n    for (member in\
            \ jsonObject) {\r\n        if (jsonObject[member] != null) {\r\n     \
            \       result = false;\r\n        }\r\n    }\r\n    return result;\r\n\
            }"
        version: "1.0.0"
    catch:
    - errors:
      - "InvalidMsisdn"
      - "ConnectionError"
      - "OperationError"
      - "UnauthorizedError"
      execute:
      - gatewayscript:
          title: "GS:ErrorHandling"
          version: "1.0.0"
          source: ""
  phase: "realized"
paths:
  /{msisdn}/bill/profile:
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/"
    parameters:
    - $ref: "#/parameters/billnumber"
    - $ref: "#/parameters/msisdn"
definitions:
  BillProfileResponse:
    type: "object"
    properties:
      billAmount:
        type: "number"
      billDate:
        type: "string"
        format: "date-time"
      paymentDate:
        type: "string"
        format: "date-time"
      amountDue:
        type: "number"
      paymentStatus:
        type: "string"
        enum:
        - "PAID"
        - "UNPAID"
        - "GRACE"
        - "LATE"
        - "NEUTRAL"
        - "UNKNOWN"
        - "NOBILL"
      totalBeforeVAT:
        type: "number"
      taxCharges:
        type: "number"
      otherChargesAndCredits:
        type: "number"
      orderCharges:
        type: "number"
      billPeriod:
        type: "object"
        properties:
          billDateFrom:
            type: "string"
            format: "date-time"
          billDateTo:
            type: "string"
            format: "date-time"
      nextBillDate:
        type: "string"
        format: "date-time"
      balanceBroughtForward:
        type: "number"
      billDiscounts:
        type: "number"
      latePaymentDetails:
        $ref: "#/definitions/LatePaymentDetails"
      latePaymentChargeDetailsList:
        type: "array"
        items:
          $ref: "#/definitions/OneTimeCharge"
      recycleCredit:
        type: "number"
      recycleChange:
        type: "number"
      extraChargesRecommendation:
        type: "string"
      defaultLPFCharge:
        type: "number"
      multiMsisdn:
        type: "boolean"
      lpfaddedToBill:
        type: "boolean"
      msisdnBillDetails:
        type: "array"
        items:
          $ref: "#/definitions/MsisdnBillDetails"
  LatePaymentDetails:
    type: "object"
    properties:
      showBannerMessage:
        type: "boolean"
      latePaymentFeeStatus:
        type: "string"
        enum:
        - "NONE"
        - "ELIGIBLE"
        - "APPLIED"
      billPaymentStatus:
        type: "string"
        enum:
        - "PAID"
        - "UNPAID"
        - "GRACE"
        - "LATE"
        - "NEUTRAL"
        - "UNKNOWN"
        - "NOBILL"
      latePaymentFeeScheduledDate:
        type: "string"
      latePaymentFee:
        type: "number"
  MsisdnBillDetails:
    type: "object"
    properties:
      msisdn:
        type: "string"
      billTotalWithoutVAT:
        type: "number"
  OneTimeCharge:
    type: "object"
    properties:
      appliedDate:
        type: "string"
      charge:
        type: "number"
      billNumber:
        type: "string"
      productName:
        type: "string"
tags: []
parameters:
  msisdn:
    name: "msisdn"
    type: "string"
    required: true
    in: "path"
  billnumber:
    name: "billnumber"
    type: "string"
    required: false
    in: "query"
  x-authcode:
    name: "x-authcode"
    type: "string"
    required: true
    in: "header"
