info:
  version: 1.0.0
  title: product-authservice
  name: product-authservice
gateways:
- datapower-gateway
product: 1.0.0
visibility:
  view:
    enabled: true
    type: public
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: authenticated
    tags: []
    orgs: []
plans:
  default:
    title: Default Plan
    description: Default Plan
    approval: false
    rate-limits:
      default:
        value: 100/hour
        hard-limit: false
apis:
  authservice:
    $ref: 20180905\151056\authservice_1.0.0.yaml
