info:
  name: product-apiassist-ref
  title: product-apiassist-ref
  version: 2.0.0
gateways:
- datapower-gateway
product: 1.0.0
visibility:
  view:
    enabled: true
    type: public
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: authenticated
    tags: []
    orgs: []
plans:
  default:
    title: Default Plan
    description: Default Plan
    approval: false
    rate-limits:
      default:
        value: 100/hour
        hard-limit: false
apis:
  o2apic-authservice:
    $ref: 20180905\153908\o2apic-authservice_1.0.0.yaml
  o2apic-novum-configapi:
    $ref: 20180905\153908\o2apic-novum-configapi_1.0.0.yaml
