swagger: "2.0"
info:
  title: SOATime
  x-ibm-name: soatime
  version: 1.0.0
schemes:
- https
produces:
- application/xml
consumes:
- application/xml
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - gatewayscript:
        version: 1.0.0
        title: gatewayscript
        source: |-
          apim.setvariable('message.headers.SOAPAction', '');
          apim.setvariable('message.headers.content-type','application/xml');
          //var key = apim.getvariable('request.parameters.msisdn');
          //apim.setvariable('msisdnKey',key);

          //var orgName = apim.getvariable('api.org.name');
          //var catalog = apim.getvariable('env.path');
          //apim.setvariable('apicURLPrefix', 'https://0.0.0.0:9443/'+orgName+'/'+catalog);
          //var timeURL = apim.getvariable('apicURLPrefix')+'/'+'time';
          //apim.setvariable('timeURL', timeURL);

          apim.setvariable('message.body','<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken><wsse:Username/><wsse:Password/><wsse:Nonce/><wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"/></wsse:UsernameToken><wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsu:Created/><wsu:Expires/></wsu:Timestamp></wsse:Security></soapenv:Header><soapenv:Body><vad:getNonDataAllowance_2 xmlns:vad="http://soa.o2.co.uk/viewallowancedata_2"><vad:account><ns1:portalID xmlns:ns1="http://soa.o2.co.uk/coredata_1"/><ns1:msisdn xmlns:ns1="http://soa.o2.co.uk/coredata_1"/><ns1:accountDetail xmlns:ns1="http://soa.o2.co.uk/coredata_1"><ns1:billingAccountType>MOBILE</ns1:billingAccountType><ns1:accountNumber>447812123454</ns1:accountNumber><ns1:msisdn>447812123454</ns1:msisdn></ns1:accountDetail></vad:account><vad:allowanceCategory/></vad:getNonDataAllowance_2></soapenv:Body></soapenv:Envelope>');
    - xslt:
        version: 1.0.0
        title: xslt
        input: true
        source: |-
          <xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dp="http://www.datapower.com/extensions" xmlns:func="http://exslt.or/functions" xmlns:apim="http://www.ibm.com/apimanagement" extension-element-prefixes="dp func apim">
              <xsl:output method="xml" omit-xml-declaration="yes" indent="yes"/>
              <xsl:import href="local:///isp/policy/apim.custom.xsl" />
              <xsl:strip-space elements="*"/>
                  <xsl:variable name="dateNow" select="current-dateTime()"/>
              <xsl:variable name="dateNow2" select="current-date()"/>
          <xsl:template match="/">
          <FL><xsl:value-of select="format-dateTime($dateNow, '[Y0001][M01][D01]')"/></FL>
          </xsl:template>
          </xsl:stylesheet>
    catch: []
  gateway: datapower-gateway
  type: rest
paths:
  /SOAtime:
    get:
      responses:
        "200":
          description: soatime
          schema:
            type: string
      consumes: []
      produces: []
      parameters: []
    post:
      responses:
        "200":
          description: soatime
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
      - name: msisdn
        type: string
        in: header
        required: true
    parameters: []
