swagger: "2.0"
info:
  title: Time
  x-ibm-name: time
  version: 1.0.0
schemes:
- https
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - gatewayscript:
        version: 1.0.0
        title: gatewayscript
        source: |-
          var now = new Date();
          apim.setvariable('message.body', now);
    catch: []
  gateway: datapower-gateway
  type: rest
paths:
  /time:
    get:
      responses:
        "200":
          description: time
          schema:
            type: string
      consumes: []
      produces: []
      parameters: []
    post:
      responses:
        "200":
          description: postTime
          schema:
            type: string
      consumes: []
      produces: []
      parameters: []
