swagger: "2.0"
info:
  title: o2apic-phoneserviceproxy
  x-ibm-name: o2apic-phoneserviceproxy
  version: 1.0.0
schemes:
- https
basePath: /ps
produces:
- application/json
- application/xml
consumes:
- application/json
- application/xml
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    aaaConfigURL:
      value: ""
      description: URL for AAA configuration file
      encoded: false
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  catalogs:
    sandbox:
      properties:
        aaaConfigURL: https://0.0.0.0:9443/o2apic/sandbox/config/aaaconfig
    dev:
      properties:
        aaaConfigURL: https://0.0.0.0:9443/o2apic/dev/config/aaaconfig
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - invoke:
        version: 1.0.0
        title: Invoke-AAAConfig
        timeout: 60
        verb: GET
        cache-response: time-to-live
        cache-ttl: 599
        stop-on-error:
        - ConnectionError
        target-url: $(aaaConfigURL)
    catch: []
  gateway: datapower-gateway
  type: rest
paths:
  /phone/consumer/CURRENT/paym:
    parameters:
    - name: uid
      type: string
      in: query
    - name: authorization
      type: string
      in: header
    get:
      responses:
        "200":
          description: Success
          schema:
            type: integer
      consumes: []
      produces: []
      parameters: []
