swagger: "2.0"
info:
  title: sample
  x-ibm-name: sample
  version: 1.0.0
schemes:
- https
basePath: /demo
produces:
- application/json
- application/xml
consumes:
- application/json
- application/xml
security:
- clientIdHeader: []
  clientIdSecret: []
securityDefinitions:
  clientIdSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - invoke:
        version: 1.0.0
        title: invoke
        timeout: 60
        verb: GET
        cache-response: protocol
        cache-ttl: 900
        target-url: http://172.31.209.143:8425/phone/v2/consumer/CURRENT/paym/bill/profile
  gateway: datapower-gateway
  type: rest
paths:
  /stub:
    get:
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
      consumes: []
      produces: []
      parameters: []
