swagger: "2.0"
info:
  title: Test-UDP
  x-ibm-name: test-udp
  version: 1.0.0
schemes:
- https
basePath: /test
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - ip-basicauth-aaa:
        version: 1.0.0
        title: ip-basicauth-aaa
    catch: []
  gateway: datapower-gateway
  type: rest
paths:
  /checkauthorization:
    get:
      responses:
        "200":
          description: Success
          schema:
            type: integer
      consumes: []
      produces: []
      parameters: []
    parameters:
    - name: authorization
      type: string
      in: header
