swagger: "2.0"
info:
  title: Test-UDP
  x-ibm-name: test-udp
  version: 1.0.0
schemes:
- https
basePath: /ps
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - fetch-configs:
        version: 1.0.0
        title: fetch-configs
        fileType: xml
        responseContext: fetchResponse
        fileName: aaaconfig
    - xslt:
        version: 1.0.0
        title: xslt
        input: false
        source: "<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"
          xmlns:apim=\"http://www.ibm.com/apimanagement\" xmlns:dp=\"http://www.datapower.com/extensions\"
          extension-element-prefixes=\"dp\" exclude-result-prefixes=\"dp apim\"> \n
          \   <!-- Contains the APIM functions --> \n    <xsl:include href=\"local:///isp/policy/apim.custom.xsl\"
          />\n    <xsl:template match=\"/\">\n        <xsl:copy-of select=\"dp:variable('var://context/fetch-configs/fetchResponse')\"/>\n
          \   </xsl:template>\n</xsl:stylesheet>"
    catch: []
  gateway: datapower-gateway
  type: rest
paths:
  /v1/device/auth:
    get:
      responses:
        "200":
          description: Success
          schema:
            type: integer
      consumes: []
      produces: []
      parameters: []
    parameters:
    - name: authorization
      type: string
      in: header
