swagger: "2.0"
info:
  title: validateToken
  x-ibm-name: validatetoken
  version: 1.0.0
schemes:
- https
basePath: /auth
produces:
- application/json
consumes:
- application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
    - gatewayscript:
        version: 1.0.0
        title: gatewayscript
        source: |-
          apim.setvariable('message.headers.cache-control', 'no-cache');
          apim.setvariable('message.headers.apigw-proof-requirement', 'user_id signed_in');
          apim.setvariable('message.headers.apigw-chained-access-token-client-id', 'auth');
          apim.setvariable('message.headers.content-type', 'application/json');
    - invoke:
        version: 1.0.0
        title: invoke
        timeout: 60
        verb: GET
        cache-response: no-cache
        cache-ttl: 900
        target-url: https://auth.ref.o2.co.uk/auth/v1/tokeninfo
    - gatewayscript:
        version: 1.0.0
        title: gatewayscript
        source: |-
          var uid = apim.getvariable('message.headers.apigw-chained-access-token');
          apim.setvariable('message.headers.uid', uid);
          //var msg = {};
          //msg.head = uid;
          //apim.setvariable('message.body', msg);
    - invoke:
        version: 1.0.0
        title: ""
        timeout: 60
        verb: GET
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        target-url: https://www.mocky.io/v2/5185415ba171ea3a00704eed
    catch: []
  gateway: datapower-gateway
  type: rest
paths:
  /validateToken:
    get:
      responses:
        "200":
          description: success
          schema:
            type: integer
      consumes: []
      produces: []
      parameters: []
    parameters:
    - name: authorization
      type: string
      in: header
